server {
    charset utf-8;
    client_max_body_size 128M;

    listen 80;

    server_name _;
    root        /app/web;
    index       index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
        expires 7d;
        access_log off;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
    #error_page 404 /404.html; # Oo

    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        fastcgi_pass php:9000;

        fastcgi_read_timeout 42000s;
    }

    location ~ /\.(ht|svn|git) {
        deny all;
    }
}
